deployment:
  name: "{{ kebabcase .Chart.Name }}-deployment"
  replicas: 3

Postgres:
  prometheus-postgres-exporter:
    config:
      datasource:
        host: grade-book-db
        user: "postgres"
        password: "otus"
        database: "postgres"
  name: "grade-book-database"
  postgres: 
    host: "{{ .Values.Postgres.service.name }}"
    username: postgres
    password: otus
  service:
    name: "grade-book-db"
  

application:
  port: 8080
  
monitor:
  name: "{{ kebabcase .Chart.Name }}-monitor"

service:
  name: "{{ kebabcase .Chart.Name }}-service"
  port: 80
  type: ClusterIP

limits:
  cpu: "500m"
  memory: "500Mi"
  
image:
  repository: registry.gitlab.com/lms-project-otus
  image: gradeboookmicroservice
  version: latest

livenessProbe:
  path: /health
  timeout: 5
  period: 5
  delay: 20
  
readinessProbe:
  path: /api/v1/lessons
  period: 20
  timeout: 20
  delay: 20

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1
  
ingress:
  name: "{{ kebabcase .Chart.Name }}-ingress"
  className: nginx
  host: "lms.ipgolenischev.ru"
  prefix: /gradebook
  
postgresSecret:
  name: "{{ .Values.Postgres.name }}-application-secret"

postgresConfigMap:
  name: "{{ .Values.Postgres.name }}-config"