include: 
  - ./.deploy/CI/dotnet.yml
  - ./.deploy/CI/docker.yml
  - ./.deploy/CI/helm.yml
stages:
  - build
  - test
  - containerize
  - deploy
variables:
  CHART_PATH: ./.deploy/Helm/Charts/GradeBookMicroservice
  SOLUTION_NAME: GradeBookMicroservice
  SOLUTION_FOLDER: ./src
  SOLUTION_PATH: $SOLUTION_FOLDER/$SOLUTION_NAME.sln
  EXECUTABLE_PROJECT_PREFIX: WebHost
  CHART: grade-book-microservice
  
build-job:
  stage: build
  extends: .build-application-part

test-job:
  stage: test
  extends: .dotnet-code-action
  script:
    - dotnet test $SOLUTION_PATH

docker-build-job:
  variables:
    DOCKERFILE_PATH: src/Presentation/GradeBookMicroservice.WebHost/Dockerfile
    SITE_NAME: $SOLUTION_NAME.$EXECUTABLE_PROJECT_PREFIX
    PROJECT_PATH: $SOLUTION_FOLDER
    DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME
  extends: .docker-image-build

helm-validate:
  stage: containerize
  extends: .helm-validate

helm-build:
  stage: containerize
  variables:
    CHART: $CHART
    SOLUTION_NAME: $SOLUTION_NAME
  extends: .helm-build