version: '3.9'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "otus"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "otus" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  webhost:
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SiteName=Otus.Teaching.PromoCodeFactory.WebHost
        - ProjectPath=/src
    ports:
      - "4040:8080"
    depends_on:
      db:
        condition: service_healthy
