services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - database.env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "$POSTGRES_USERNAME", "-U", "$POSTGRES_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SiteName=GradeBookMicroservice.WebHost
        - ProjectPath=./src
    ports:
      - "8080:8080"
    env_file:
      - application.env
    healthcheck:
      test: ["CMD","curl", "http://localhost:8080/health"]
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
