services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "otus"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
 
 
 