apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.name . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: http
spec:
  selector:
    app: {{ tpl .Values.deployment.name . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.port }}
  type: {{ .Values.service.type }}
  