apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grade-book-database-pvc
  namespace: grade-book-microservice
spec:
  storageClassName: grade-book-database-storage-class-minikube
  resources:
    requests:
      storage: "1Gi"
      
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
